### PR TITLE
lua client driver for KyotoTycoon using its binary protocol at ngx_lua

### PR DESCRIPTION
**Pull request by sjnam**
Lua client driver for KyotoTycoon using its binary protocol

### CODE REVIEW

**Comment by bungle** [comment]
Thanks but should you perhaps rename this project so that it can be installed alongside Cloudflares resty.kyototycoon?

**Comment by sjnam** [comment]
@bungle 
KT has three protocols, TSV-RPC, RESTful, and Binary. The first two are base on HTTP protocol. My lua-resty-kyototycoon implements binary protocol but cloudfare's is TSV-RPC on HTTP protocol. Thanks.

**Comment by bungle** [comment]
@sjnam, I understand, but your library is `resty.kyototycoon` and CloudFlare's is also `resty.kyototycoon`. You could rename yours (as the CloudFlare's was prior work) to say `resty.kyototycoon-bin` or something so that the libs don't share the same namespace and same files. E.g. you cannot install both in the same namespace (and you need to manually but them in separate places).

**Comment by sjnam** [comment]
@bungle Thank you for your advice. But I think that anyone who want to use lua KT client on openresty should choose one of the two, cloudflare's or mine. She or he don't have to install both in the same namespace because they has the same or similar functions.

**Comment by sjnam** [comment]
@bungle I renamed module name to "resty.kyototycoon.binary" :-)

**Comment by bungle** [comment]
@sjnam well, yes, but one OpenResty Server can service multiple applications, some using CloudFlare, and maybe newer ones using yours. I think the change of the name is good. In some point you could maybe try to merge with CloudFlare's.

**Pull request merged**
